/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './icon.component';
const styles_IconComponent:any[] = ([] as any[]);
export const RenderType_IconComponent:import0.RendererType2 = import0.ɵcrt({
  encapsulation: 2,
  styles: styles_IconComponent,
  data: {}
}
);
export function View_IconComponent_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵeld(0,(null as any),(null as any),3,':svg:svg',[
      [
        'class',
        'icon'
      ]
      ,
      [
        'height',
        '24px'
      ]
      ,
      [
        'preserveAspectRatio',
        'xMidYMin'
      ]
      ,
      [
        'viewBox',
        '0 0 24 24'
      ]
      ,
      [
        'width',
        '24px'
      ]
      ,
      [
        'x',
        '0px'
      ]
      ,
      [
        'xmlns',
        'http://www.w3.org/2000/svg'
      ]
      ,
      [
        'y',
        '0px'
      ]

    ]
    ,(null as any),(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n    '])),
      (l()(),import0.ɵeld(0,(null as any),(null as any),0,':svg:use',([] as any[]),[[
        1,
        ':xlink:href',
        0
      ]
    ],(null as any),(null as any),(null as any),(null as any))),
    (l()(),import0.ɵted((null as any),['\n'])),
    (l()(),import0.ɵted((null as any),['\n']))
  ]
  ,(null as any),(ck,v) => {
    var co:import1.IconComponent = v.component;
    const currVal_0:any = ((co.baseUrl + '#') + co.name);
    ck(v,3,0,currVal_0);
  });
}
function View_IconComponent_Host_0(l:any):import0.ɵViewDefinition {
  return import0.ɵvid(0,[
    (l()(),import0.ɵeld(0,(null as any),(null as any),1,'icon',([] as any[]),(null as any),(null as any),(null as any),View_IconComponent_0,RenderType_IconComponent)),
    import0.ɵdid(49152,(null as any),0,import1.IconComponent,([] as any[]),(null as any),(null as any))
  ]
  ,(null as any),(null as any));
}
export const IconComponentNgFactory:import0.ComponentFactory<import1.IconComponent> = import0.ɵccf('icon',import1.IconComponent,View_IconComponent_Host_0,{name: 'name'},{},([] as any[]));
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3RvbnlsZWZsZXIvcHJvamVjdHMvYW5ndWxhci1zdmctaWNvbnMvc3JjL2ljb25zL2ljb24uY29tcG9uZW50Lm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3RvbnlsZWZsZXIvcHJvamVjdHMvYW5ndWxhci1zdmctaWNvbnMvc3JjL2ljb25zL2ljb24uY29tcG9uZW50LnRzIiwibmc6Ly8vVXNlcnMvdG9ueWxlZmxlci9wcm9qZWN0cy9hbmd1bGFyLXN2Zy1pY29ucy9zcmMvaWNvbnMvaWNvbi5jb21wb25lbnQudHMuSWNvbkNvbXBvbmVudC5odG1sIiwibmc6Ly8vVXNlcnMvdG9ueWxlZmxlci9wcm9qZWN0cy9hbmd1bGFyLXN2Zy1pY29ucy9zcmMvaWNvbnMvaWNvbi5jb21wb25lbnQudHMuSWNvbkNvbXBvbmVudF9Ib3N0Lmh0bWwiXSwic291cmNlc0NvbnRlbnQiOlsiICIsIlxuPHN2ZyBjbGFzcz1cImljb25cIlxuICAgICB4PVwiMHB4XCIgeT1cIjBweFwiXG4gICAgIHhtbG5zPVwiaHR0cDovL3d3dy53My5vcmcvMjAwMC9zdmdcIlxuICAgICB3aWR0aD1cIjI0cHhcIlxuICAgICBoZWlnaHQ9XCIyNHB4XCJcbiAgICAgcHJlc2VydmVBc3BlY3RSYXRpbz1cInhNaWRZTWluXCJcbiAgICAgdmlld0JveD1cIjAgMCAyNCAyNFwiPlxuICAgIDx1c2UgW2F0dHIueGxpbms6aHJlZl09XCJiYXNlVXJsKycjJytuYW1lXCIgLz5cbjwvc3ZnPlxuIiwiPGljb24+PC9pY29uPiJdLCJtYXBwaW5ncyI6IkFBQUE7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7SUNBQTtJQUNBO01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O01BQUE7UUFBQTtRQUFBO01BQUE7O0lBQUE7S0FBQTtJQU15QjtNQUNyQjtRQUFBO1FBQUE7UUFBQTtNQUFBO0lBQUE7SUFBNEM7SUFDMUM7Ozs7SUFERztJQUFMLFNBQUssU0FBTDs7Ozs7SUNSSjtnQkFBQTs7OzsifQ==
