/**
 * @fileoverview This file is generated by the Angular template compiler.
 * Do not edit.
 * @suppress {suspiciousCode,uselessCode,missingProperties,missingOverride}
 */
 /* tslint:disable */


import * as import0 from '@angular/core';
import * as import1 from './icon.module';
class IconModuleInjector extends import0.ɵNgModuleInjector<import1.IconModule> {
  _IconModule_0:import1.IconModule;
  constructor(parent:import0.Injector) {
    super(parent,([] as any[]),([] as any[]));
  }
  createInternal():import1.IconModule {
    this._IconModule_0 = new import1.IconModule();
    return this._IconModule_0;
  }
  getInternal(token:any,notFoundResult:any):any {
    if ((token === import1.IconModule)) { return this._IconModule_0; }
    return notFoundResult;
  }
  destroyInternal():void {
  }
}
export const IconModuleNgFactory:import0.NgModuleFactory<import1.IconModule> = new import0.NgModuleFactory<any>(IconModuleInjector,import1.IconModule);
//# sourceMappingURL=data:application/json;base64,eyJmaWxlIjoiL1VzZXJzL3RvbnlsZWZsZXIvcHJvamVjdHMvYW5ndWxhci1zdmctaWNvbnMvc3JjL2ljb25zL2ljb24ubW9kdWxlLm5nZmFjdG9yeS50cyIsInZlcnNpb24iOjMsInNvdXJjZVJvb3QiOiIiLCJzb3VyY2VzIjpbIm5nOi8vL1VzZXJzL3RvbnlsZWZsZXIvcHJvamVjdHMvYW5ndWxhci1zdmctaWNvbnMvc3JjL2ljb25zL2ljb24ubW9kdWxlLnRzIl0sInNvdXJjZXNDb250ZW50IjpbIiAiXSwibWFwcGluZ3MiOiJBQUFBOzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7OzsifQ==
